FROM python:3.7.0-alpine3.8
RUN pip3 install boto3

WORKDIR /tmp

ARG ACCESS_KEY_ID
ARG SECRET_ACCESS_KEY
ENV AWS_AZ=us-east-1
ENV AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY

ADD * /tmp/

# COPY service/*.py /tmp/

